# Permalinks
permalink:        pretty

# Setup
title:            Gary's Zone
tagline:          'Blog'
description:      'Blog by GaryNg with tutorials, softwares and many more. Enjoy!'
url:              'http://garyng.github.io'
#url:              'http://garyszone.me'
version:          '2.0'

author:
  name:           'GaryNg'
  url:            ''
  email:          'garyng.zhongbo@gmail.com'

paginate:         20

markdown_ext:     markdown,mdown,mkdown,mkdn,mkd,md

gems:
  - jekyll-sitemap
  - jekyll-paginate

# Style
excerpt_separator: '<!-- More -->'

#Travis CI
exclude:          [vendor]
