# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Gary's Zone
tagline:          'Blog'
description:      'Blog by GaryNg with tutorials, softwares and many more. Enjoy!'
#url:              'http://garyng.github.io'
url:              'http://garyszone.me'
isBeta:           true

author:
  name:           'GaryNg'
  url:            ''
  email:          'garyng.zhongbo@gmail.com'

paginate:         5

markdown_ext:     markdown,mdown,mkdown,mkdn,mkd,md
