# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Gary's Zone
tagline:          'Blog'
description:      'Blog by GaryNg with tutorials, softwares and many more. Enjoy!'
url:              'http://garyng.github.io'

author:
  name:           'GaryNg'
  url:            ''

paginate:         5

markdown_ext:     markdown,mdown,mkdown,mkdn,mkd,md

github:
  repo:           ''

defaults:
 -
   scope:
    path: ""
    type: "post"
   values:
    comments: "true"